language: node_js
dist: xenial

jobs:
  include:
    - name: Lint
      node_js: stable
      script: npm run test:lint
    - name: Test on Stable Node.js
      node_js: stable
      script: npm run test:tap
    - name: Test on Node.js 12
      node_js: 12
      script: npm run test:tap
    - name: Test on Node.js 10
      node_js: 10
      script: npm run test:tap
    - name: Test on Node.js 8
      node_js: 8
      script: npm run test:tap
    - name: Test on Node.js 6
      node_js: 6
      script: npm run test:tap
    - name: Test on Node.js 4
      node_js: 4
      script: npm run test:tap
    - name: Run browser tests
      node_js: stable
      script: xvfb-run --auto-servernum npm run test:browser
      services:
        - xvfb
