language: node_js
dist: xenial
node_js:
  - stable
  - '12'
  - '10'
  - '8'
  - '6'
  - '4'

test:
  - npm run test:lint
  - npm run test:tap
  - xvfb-run --auto-servernum npm run test:browser

services:
  - xvfb
