language: node_js
os:
  - linux
  - windows
node_js:
  - '10'
  - '8'
  - '6'
  - '4'

matrix:
  include:
    - os: linux
      node_js: stable
    - os: windows
      node_js: latest

before_script:
  - 'export DISPLAY=":99.0"'
  - 'Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &'

addons:
  apt:
    packages:
      - 'xvfb'

cache:
  directories:
    - ~/.npm
