language: node_js
node_js:
  - stable
  - '8'
  - '6'
  - '4'
cache:
  directories:
    - ~/.npm

addons:
  apt:
    packages:
      - 'xvfb'
    install:
      - 'export DISPLAY=":99.0"'
      - 'Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &'
      - 'npm install'
